package com.server.mock.exception;

public class UserAlreadyExistsException extends Exception{
    public void fun(){

    }
}
